package com.hamstoo.models

sealed trait Position

/**
  * Data class containing frontend comment data, that is directly serialised into and deserialized from JSON. Data
  * stored here is completely generated by frontend.
  * @param path     X-path
  * @param text     Note text
  * @param offsetX  Horizontal offset inside path element. (?)
  * @param offsetY  Vertical offset inside path element. (?)
  */
case class InlineNotePosition(path: String,
                              text: String,
                              offsetX: Double,
                              offsetY: Double) extends Position

/** XML XPath and text located at that path. */
case class HLPositionElement(path: String, text: String)

/** A highlight can stretch over a series of XPaths.  `initIndex` is the `startOffset` character in the first one. */
case class HLPosition(elements: Seq[HLPositionElement], initIndex: Int) extends Position
