/*
 * Copyright (C) 2017-2018 Hamstoo, Inc. <https://www.hamstoo.com>
 */
package com.hamstoo.models

import java.util.UUID

import com.github.dwickern.macros.NameOf.nameOf
import com.hamstoo.utils.{TIME_NOW, TimeStamp}
import reactivemongo.bson.{BSONDocumentHandler, Macros}

/**
  * We store user's recommendations in a mongoDB collection
  * @param userId - user's UUID
  * @param source - One of the values from RecSourceEnum (as a String).
  * @param params - detailed about what generated the recommendation(i.e. recent autogenerated keywords)
  * @param url - a URI where the recommendation is hosted
  * @param ts - the date when the recommendation was saved
  */
case class Recommendation(userId: UUID,
                          source: String,
                          params: Map[String, String],
                          url: String,
                          ts: TimeStamp = TIME_NOW)

object Recommendation extends BSONHandlers {

  val USR      : String =      Mark.USR;        assert(USR       == nameOf[Recommendation](_.userId))
  val TIMESTAMP: String = UserStats.TIMESTAMP;  assert(TIMESTAMP == nameOf[Recommendation](_.ts))

  implicit val recommendationHandler: BSONDocumentHandler[Recommendation] = Macros.handler[Recommendation]
}